# Generated by Django 4.1 on 2022-08-15 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
            ],
            options={
                'verbose_name': 'Режиссёр',
                'verbose_name_plural': 'Режиссёры',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('poster', models.ImageField(height_field=200, upload_to='', verbose_name='Изображение', width_field=300)),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2022)], verbose_name='Год')),
                ('duration', models.CharField(max_length=4, verbose_name='Продолжительность')),
                ('premiere', models.CharField(max_length=16, verbose_name='Премьера фильма')),
                ('film_file', models.FileField(upload_to='')),
                ('country', models.ManyToManyField(to='films.country')),
                ('genre', models.ManyToManyField(to='films.genre')),
                ('producer', models.ManyToManyField(to='films.producer')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
