# Generated by Django 4.1 on 2022-08-20 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_remove_film_country_film_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='country',
            new_name='country_film',
        ),
        migrations.AddField(
            model_name='country',
            name='film_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='films.film'),
            preserve_default=False,
        ),
    ]
