# Generated by Django 4.1 on 2022-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='producer',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
