# Generated by Django 4.1 on 2022-08-20 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_country_film_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='film_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='films.film'),
        ),
    ]
