# Generated by Django 4.1 on 2022-08-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_alter_country_film_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='film_country',
            new_name='film',
        ),
        migrations.RemoveField(
            model_name='film',
            name='country_film',
        ),
    ]
