# Generated by Django 4.1 on 2022-09-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_user', '0002_alter_customuser_email_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=300, verbose_name='Текст'),
        ),
    ]
